### ISSUE TITLE
No-Shadow Lint Rule Update

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/code-standards#33]
#### Describe the desired behavior
```
"no-shadow": "off",
"@typescript-eslint/no-shadow": ["error"]
```

#### Describe the current behavior
uses the built-in no-shadow rule

#### Is this request related to a current issue?
No, but I noticed it when working on another project and using our linting rules.

#### Additional Context
This error will trigger ("XXX is already declared in the upper scope") anytime you try to declare an enum using our existing rule set.

https://stackoverflow.com/questions/63961803/eslint-says-all-enums-in-typescript-app-are-already-declared-in-the-upper-scope

**Comment by emclaug2** [comment]
Closed in #51
