### ISSUE TITLE
Eslint Naming Convention Update

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/code-standards#55]
#### Describe the bug
Eslint attempting to apply naming conventions to string keys in objects.

#### What is the expected behavior?
String keys should be exempt from the rule.

#### What are the steps to reproduce?
--

#### Anything else to add?
Some info here: https://github.com/typescript-eslint/typescript-eslint/issues/1483

**Comment by bkarambe** [comment]
The end goal is eslint ignore any quoted object keys but still apply the rules to the non-quoted keys.
